message(STATUS "Project name: ${PROJECT_NAME}")

if(BUILD_SHARED_LIBS)
	message(STATUS "Library Type: Dynamic")
else()
	message(STATUS "Library Type: Static")
endif()

# config directories
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/${OUT_DIR}/lib" CACHE PATH "" FORCE)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/${OUT_DIR}/lib" CACHE PATH "" FORCE)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/${OUT_DIR}/bin" CACHE PATH "" FORCE)

# Directory output files for multi config generators
foreach(OUTPUTCONFIG ${CMAKE_CONFIGURATION_TYPES})
	string(TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG)
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${CMAKE_SOURCE_DIR}/${OUT_DIR}/bin" CACHE PATH "" FORCE)
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${CMAKE_SOURCE_DIR}/${OUT_DIR}/lib" CACHE PATH "" FORCE)
	set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${CMAKE_SOURCE_DIR}/${OUT_DIR}/lib" CACHE PATH "" FORCE)
endforeach()

set(CMAKE_INSTALL_INCLUDEDIR "${CMAKE_SOURCE_DIR}/${OUT_DIR}/include")

if(WIN32)
	set(CMAKE_USE_RELATIVE_PATHS "1")

	# Set compiler flags for "release"
	set(CMAKE_CXX_FLAGS_RELEASE "/MD /MP /Ox /Ob2 /Oi /Ot /fp:fast /D NDEBUG /openmp")
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/MD /Zi /MP /Ox /Ob2 /Oi /Ot /fp:fast /D NDEBUG /openmp")
	set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MP /openmp")
endif(WIN32)

if(UNIX)
	set(CMAKE_USE_RELATIVE_PATHS "1")

	# Set compiler flags for "release"
	set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG -fopenmp")
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -DNDEBUG -march=native -fopenmp")
	set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fopenmp")
endif(UNIX)

# c++
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)